services: # Each service is a container in the project
  postgres: # Name of the service, used for database container
    image: postgres:15-alpine #What version of the service should be used in the container
    container_name: postgres-db # Sets a fixed name for the container so that it doesn't need to be generated every time the project is ran
    environment: # credentials to be used in container, the values will be gotten from env file when the project is ran
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}
    volumes: # where data is stored, name of volume:path to volume
      - postgres-data:/var/lib/postgresql/data
    ports: # port the service will run on. host:container
      - "5432:5432"
    healthcheck: # checks if the service is healthy
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"] # checks if the database is ready to accept connections
      interval: 10s # how often to check
      timeout: 5s # how long to wait for a response
      retries: 5 # how many times to retry before marking the service as unhealthy
    restart: unless-stopped # if the container crashes, restarts automatically
  backend: # Name of backend service
    build: ./backend # path to the backend folder
    container_name: csharp_backend
    environment:
      # 
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PW} 
    depends_on: # The services the backend container depends on
      postgres:
        condition: service_healthy # Waits for the postgres service to be healthy before starting the backend container
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "5000:8080"
    depends_on:
      - backend

volumes: # volume name
  postgres-data: # db volume

